codes={
"Restart marker replay" : "110",
"Service ready in nnn minutes" : "120",
"Data connection already open; transfer starting" : "125",
"File status okay; about to open data connection" : "150",
"Command not implemented, superfluous at this site" : "202",
"System status, or system help reply" : "211",
"Directory status" : "212",
"File status" : "213",
"Help message" : "214",
"NAME system type. Where NAME is an official system name from the registry kept by IANA" : "215",
"Service ready for new user" : "220",
"Service closing control connection" : "221",
"Data connection open; no transfer in progress" : "225",
"Closing data connection. Requested file action successful" : "226",
"Entering Passive Mode" : "227",
"Entering Long Passive Mode" : "228",
"Entering Extended Passive Mode" : "229",
"User logged in, proceed. Logged out if appropriate" : "230",
"User logged out; service terminated" : "231",
"Logout command noted, will complete when transfer done" : "232",
"Specifies that the server accepts the authentication mechanism specified by the client, and the exchange of security data is complete. A higher level nonstandard code created by Microsoft" : "234",
"Requested file action okay, completed" : "250",
"PATHNAME created" : "257",
"User name okay, need password" : "331",
"Need account for login" : "232",
"Requested file action pending further information" : "350",
"Service not available, closing control connection. This may be a reply to any command if the service knows it must shut down" : "421",
"Can't open data connection" : "425",
"Connection closed; transfer aborted" : "426",
"Invalid username or password" : "430",
"Requested host unavailable" : "434",
"Requested file action not taken" : "450",
"Requested action aborted. Local error in processing" : "451",
"Requested action not taken. Insufficient storage space in system.File unavailable" : "452",
"Syntax error in parameters or arguments" : "501",
"Command not implemented" : "502",
"Bad sequence of commands" : "503",
"Command not implemented for that parameter" : "504",
"Not logged in" : "530",
"Need account for storing files" : "532",
"Could Not Connect to Server - Policy Requires SSL" : "534",
"Requested action not taken. File unavailable" : "550",
"Requested action aborted. Page type unknown" : "551",
"Requested file action aborted. Exceeded storage allocation" : "552",
"Requested action not taken. File name not allowed" : "553",
"Integrity protected reply" : "631",
"Confidentiality and integrity protected reply" : "632",
"Confidentiality protected reply" : "633",
"Connection reset by peer. The connection was forcibly closed by the remote host" : "10054",
"Cannot connect to remote server":"10060" ,
"Cannot connect to remote server. The connection is actively refused by the server" : "10061",
"Directory not empty" : "10066",
"Too many users, server is full" : "10068"
}
